### ISSUE TITLE
Huber_score_unscaled: Where is it ?

### ISSUE THREAD

**Issue by Mufabo** [RobustSP/toolbox#5]
Hi,

the function Huber_score_unscaled used in codes/04_RobustFiltering/ekf_toa_Masreliez.m line 98 is neither defined in the RobustSp nor in any native Matlab toolbox.

I've looked in the [matlab docs](https://de.mathworks.com/help/search.html?qdoc=Huber_score_unscaled&submitsearch=) and the [repo itself](https://github.com/RobustSP/toolbox/search?q=Huber_score_unscaled&unscoped_q=Huber_score_unscaled)

**Comment by RobustSP** [comment]
The option "Huber_score_unscaled" has been removed.
